src/KopSoftWms/Controllers/UserController.cs
using FluentValidation.Results;
using IServices;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SqlSugar;
using System.IO;
using System.Linq;
using YL.Core.Entity;
using YL.Core.Entity.Fluent.Validation;
using YL.NetCore.Attributes;
using YL.NetCore.NetCoreApp;
using YL.Utils.Delegate;
using YL.Utils.Extensions;
using YL.Utils.Pub;
using YL.Utils.Security;
using YL.Utils.Table;

namespace KopSoftWms.Controllers
{
    public class UserController : BaseController
    {
        private readonly ISys_userServices _userServices;
        private readonly ISys_deptServices _deptServices;
        private readonly ISys_roleServices _roleServices;

        public UserController(ISys_roleServices roleServices, ISys_deptServices deptServices, ISys_userServices userServices)
        {
            _roleServices = roleServices;
            _deptServices = deptServices;
            _userServices = userServices;
        }

        [HttpGet]
        [CheckMenu]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [OperationLog(LogType.select)]
        public ContentResult List([FromForm] Bootstrap.BootstrapParams bootstrap)
        {
            //单表
            //var express = ExpressionExt.Init<Sys_user>();
            //express.And(c => c.IsDel == 1);
            //var order = ExpressionExt.InitO<Sys_user>(bootstrap.sort);
            //if (!bootstrap.search.IsEmpty())
            //{
            //    express.And(c => c.UserName == bootstrap.search && c.UserNickname == bootstrap.search);
            //}
            //var list = _userServices.QueryableToPage(express, order, bootstrap.order, bootstrap.offset, bootstrap.limit);

            var sd = _userServices.PageList(bootstrap);
            return Content(sd);
        }

        public IActionResult Add(string id)
        {
            ViewBag.Dept = _deptServices.QueryableToList(c => c.IsDel == 1);
            ViewBag.Role = _roleServices.QueryableToList(c => c.IsDel == 1);
            var user = new Sys_user();
            if (id.IsEmpty())
            {
                return View(user);
            }
            else
            {
                user = _userServices.QueryableToEntity(c => c.UserId == SqlFunc.ToInt64(id));
                return View(user);
            }
        }

        public IActionResult Info()
        {
            var user = _userServices.QueryableToEntity(c => c.UserId == SqlFunc.ToInt64(UserDtoCache.UserId));
            return View(user);
        }

        public IActionResult UploadHeadImg(IFormFile file)
        {
            if (file == null || file.Length <= 0)
            {
                return BootJsonH((false, PubConst.File1));
            }
            string fileExt = Path.GetExtension(file.FileName).ToLower();
            var img = Path.Combine("upload", "head", PubId.GetUuid()) + fileExt;
            var filepath = Path.Combine(WebRoot, img);
            return DelegateUtil.TryExecute<IActionResult>(() =>
            {
                using (var stream = new FileStream(filepath, FileMode.CreateNew))
                {
                    file.CopyTo(stream);
                }
                var flag = _userServices.Update(new Sys_user { UserId = SqlFunc.ToInt64(UserDtoCache.UserId), HeadImg = img, ModifiedBy = UserDtoCache.UserId, ModifiedDate = DateTimeExt.DateTime }, c => new { c.HeadImg, c.ModifiedBy, c.ModifiedDate });
                return BootJsonH(flag ? (flag, PubConst.File6) : (flag, PubConst.File7));
            }, BootJsonH((false, PubConst.File5))
             );
        }

        /// <summary>
        /// 修改密码
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public IActionResult UpdatePwd()
        {
            var user = _userServices.QueryableToEntity(c => c.UserId == SqlFunc.ToInt64(UserDtoCache.UserId));
            return View(user);
        }

        [HttpPost]
        [OperationLog(LogType.update)]
        public IActionResult UpdatePwd([FromForm] Sys_user sys_User, [FromForm] string id)
        {
            //用Sys_user中的Sort接收旧密码
            if (id.IsEmptyZero())
            {
                return BootJsonH((false, PubConst.User2));
            }
            else
            {
                var user = _userServices.QueryableToEntity(c => c.UserId == SqlFunc.ToInt64(id));
                if (sys_User.Sort.ToMd5() != user.Pwd)
                {
                    return BootJsonH((false, PubConst.User4));
                }
                user.Pwd = sys_User.Pwd.ToMd5();
                user.ModifiedBy = UserDtoCache.UserId;
                user.ModifiedDate = DateTimeExt.DateTime;
                bool flag = _userServices.Update(user);
                return BootJsonH(flag ? (flag, PubConst.Update3) : (flag, PubConst.Update4));
            }
        }

        [HttpPost]
        [FilterXss]
        [OperationLog(LogType.addOrUpdate)]
        public IActionResult AddOrUpdate([FromForm] Sys_user sys_User, [FromForm] string id)
        {
            var validator = new SysUserFluent();
            ValidationResult results = validator.Validate(sys_User);
            bool success = results.IsValid;
            if (!success)
            {
                string msg = results.Errors.Aggregate("", (current, item) => (current + item.ErrorMessage + "</br>"));
                return BootJsonH((PubEnum.Failed.ToInt32(), msg));
            }
            if (id.IsEmptyZero())
            {
                if (_userServices.IsAny(c => c.UserNickname == sys_User.UserNickname))
                {
                    return BootJsonH((false, PubConst.User1));
                }
                sys_User.UserId = PubId.SnowflakeId;
                sys_User.Pwd = sys_User.Pwd.ToMd5();
                sys_User.CreateBy = UserDtoCache.UserId;
                sys_User.LoginTime = 0;
                sys_User.HeadImg = Path.Combine("upload", "head", "4523c812eb2047c39ad91f8c5de3fb31.jpg");
                bool flag = _userServices.Insert(sys_User);
                return BootJsonH(flag ? (flag, PubConst.Add1) : (flag, PubConst.Add2));
            }
            else
            {
                sys_User.UserId = id.ToInt64();
                sys_User.ModifiedBy = UserDtoCache.UserId;
                sys_User.ModifiedDate = DateTimeExt.DateTime;
                bool flag = _userServices.Update(sys_User);
                return BootJsonH(flag ? (flag, PubConst.Update1) : (flag, PubConst.Update2));
            }
        }

        [HttpGet]
        [OperationLog(LogType.delete)]
        public IActionResult Delete(string id)
        {
            var flag = _userServices.Update(new Sys_user { UserId = SqlFunc.ToInt64(id), IsDel = 0, ModifiedBy = UserDtoCache.UserId, ModifiedDate = DateTimeExt.DateTime }, c => new { c.IsDel, c.ModifiedBy, c.ModifiedDate });
            return BootJsonH(flag ? (flag, PubConst.Delete1) : (flag, PubConst.Delete2));
        }

        [HttpGet]
        [OperationLog(LogType.update)]
        public IActionResult Enable(string id, string type)
        {
            if (type == "1")
            {
                //禁用
                var flag = _userServices.Update(new Sys_user { UserId = SqlFunc.ToInt64(id), IsEabled = 0, ModifiedBy = UserDtoCache.UserId, ModifiedDate = DateTimeExt.DateTime }, c => new { c.IsEabled, c.ModifiedBy, c.ModifiedDate });
                return BootJsonH(flag ? (flag, PubConst.Enable3) : (flag, PubConst.Enable4));
            }
            else
            {
                //启用
                var flag = _userServices.Update(new Sys_user { UserId = SqlFunc.ToInt64(id), IsEabled = 1, ModifiedBy = UserDtoCache.UserId, ModifiedDate = DateTimeExt.DateTime }, c => new { c.IsEabled, c.ModifiedBy, c.ModifiedDate });
                return BootJsonH(flag ? (flag, PubConst.Enable1) : (flag, PubConst.Enable2));
            }
        }
    }
}

src/KopSoftWms/ViewComponents/DeptViewComponent.cs
using IServices;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using YL.Utils.Extensions;

namespace KopSoftWms.ViewComponents
{
    public class DeptViewComponent : ViewComponent
    {
        private readonly ISys_deptServices _deptServices;

        public DeptViewComponent(ISys_deptServices deptServices)
        {
            _deptServices = deptServices;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var dept = await _deptServices.QueryableToList(c => c.IsDel == 1).ToListAsync();
            return View(dept);
        }
    }
}

src/KopSoftWms/Views/User/Add.cshtml
@{
    Layout = "_LayoutH";
    @model Sys_user
}
@*<div id="app" v-cloak>
        <form class="form-horizontal" onsubmit="return false">
            <div class="box-body">
                <div class="form-group">
                    <label class="col-sm-2 control-label">用户名</label>
                    <div class="col-sm-10">
                        <input v-model="UserName" type="text" class="input-text" v-focus>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">昵称</label>
                    <div class="col-sm-10">
                        <input type="text" class="input-text" v-model="UserNickname">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">昵称</label>
                    <div class="col-sm-10">
                        <input type="text" class="input-text" v-model="UserNickname">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">备注</label>
                    <div class="col-sm-10">
                        <textarea v-model="Remark" class="form-control" rows="3" placeholder="备注...100个字符以内"></textarea>
                        <p class="textarea-numberbar"><em class="textarea-length">{{count}}</em>/100</p>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="pull-right box-tools">
                    <input v-on:click="addL" class="btn btn-primary radius" type="submit" v-model="submit">
                </div>
            </div>
        </form>
    </div>*@
<div id="app" v-cloak>
    <form class="form-horizontal" onsubmit="return false">
        <div class="box-body">
            @*<div class="form-group">
                    <label for="starttime" class="col-sm-2 control-label">实际开始时间</label>
                    <div class="col-md-4">
                        <input class="form-control" type="text" id="starttime" />
                    </div>
                    <label for="endtime" class="col-sm-2 control-label">实际结束时间</label>
                    <div class="col-md-4">
                        <input class="form-control" type="text" id="endtime" />
                    </div>
                </div>*@
            <table class="table table-bordered">
                <tr>
                    <td>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><span class="c-red">*</span>用户名：</label>
                            <div class="col-sm-10">
                                <input v-model="UserName" type="text" class="form-control" v-focus>
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="control-label col-sm-2"><span class="c-red">*</span>昵称：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" v-model="UserNickname">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group" v-if="UserId<=0">
                            <label class="control-label col-sm-2"><span class="c-red">*</span>初始密码：</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" autocomplete="off" value="" placeholder="密码" v-model="Pwd1">
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group" v-if="UserId<=0">
                            <label class="control-label col-sm-2"><span class="c-red">*</span>确认密码：</label>
                            <div class=" col-sm-10">
                                <input type="password" class="form-control" autocomplete="off" placeholder="确认新密码" v-model="Pwd2">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="form-group">
                            <label class="control-label col-sm-2"><span class="c-red">*</span>性别：</label>
                            <div class="col-sm-10 ">
                                <label class="radio-inline">
                                    <input type="radio" value="1" v-model="sex">男
                                </label>
                                <label class="radio-inline">
                                    <input type="radio" value="0" v-model="sex">女
                                </label>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <label class="control-label col-sm-2"><span class="c-red">*</span>手机：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" v-model="Tel">
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><span class="c-red">*</span>邮箱：</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" v-model="Email">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        @await Component.InvokeAsync("Dept")
                        @*<div class="form-group">
                                <label class="col-sm-2 control-label">部门：</label>
                                <div class="col-sm-10">
                                    <select class="form-control" v-model="DeptId">
                                        <option value="">请选择</option>
                                        @{
                                            if (ViewBag.Dept != null || ViewBag.Dept.Count > 0)
                                            {
                                                foreach (var item in ViewBag.Dept)
                                                {
                                                    <option value="@item.DeptId">@item.DeptName</option>
                                                }
                                            }
                                        }
                                    </select>
                                </div>
                            </div>*@
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">角色：</label>
                            <div class="col-sm-10">
                                <select class="form-control" v-model="RoleId">
                                    <option value="">请选择</option>
                                    @{
                                        if (ViewBag.Role != null || ViewBag.Role.Count > 0)
                                        {
                                            foreach (var item in ViewBag.Role)
                                            {
                                                <option value="@item.RoleId">@item.RoleName</option>
                                            }
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">备注：</label>
                            <div class="col-sm-10">
                                <textarea v-model="Remark" class="form-control" rows="3" placeholder="备注...100个字符以内"></textarea>
                                <p class="textarea-numberbar"><em class="textarea-length">{{count}}</em>/100</p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
            <div class="box-footer">
                <div class="pull-right box-tools">
                    <input v-on:click="addL" class="btn btn-primary radius" type="submit" v-model="submit">
                </div>
            </div>
        </div>
    </form>
</div>
@section scripts{
    <script>
        $(function () {
            parent.$("span[class='layui-layer-setwin']")[0].childNodes[1].onclick = function () {
                //var iframeH = parent.$("div[type='iframe']")[0].clientHeight;
                //parent.$("div[class='layui-layer-content']")[0].childNodes[0].style.height = 1000;
                var index = parent.layer.getFrameIndex(window.name);
                //console.info(parent.$("#layui-layer" + index)[0].style["height"]);
                parent.$("#layui-layer-iframe" + index)[0].style.height = parent.document.body.clientHeight + "px";
            };
        });
        var app = new Vue({
            el: "#app",
            data: {
                submit: "添加",
                sex: "@Model.Sex",
                Remark: "@Model.Remark",
                Tel: "@Model.Tel",
                Email: "@Model.Email",
                UserName: "@Model.UserName",
                UserNickname: "@Model.UserNickname",
                Pwd1: "",
                Pwd2: "",
                RoleId: "@Model.RoleId",
                DeptId: "@Model.DeptId",
                UserId: "@Model.UserId"
            },
            computed: {
                count: function () {
                    return this.strLength(this.Remark, false);
                }
            },
            methods: {
                addL: function () {
                    var _self = this;
                    if (_self.UserName.length <= 0) {
                        layer.msg("姓名不能为空", { icon: 2 });
                        return false;
                    }
                    if (_self.UserNickname.length <= 0) {
                        layer.msg("昵称不能为空", { icon: 2 });
                        return false;
                    }
                    if (_self.UserId.length<=0) {
                        if (_self.Pwd1.length <= 0) {
                            layer.msg("密码不能为空", { icon: 2 });
                            return false;
                        }
                        if (_self.Pwd2 !== _self.Pwd1) {
                            layer.msg("两次输入密码不一致", { icon: 2 });
                            return false;
                        }
                    }
                    if (_self.DeptId.length <= 0) {
                        layer.msg("请选择部门", { icon: 2 });
                        return false;
                    }
                    if (_self.RoleId.length <= 0) {
                        layer.msg("请选择角色", { icon: 2 });
                        return false;
                    }
                    var index = layer.load(1, {
                        shade: [0.1, '#fff'] //0.1透明度的白色背景
                    });
                    var data = {
                        id: _self.UserId,
                        UserName: _self.UserName,
                        UserNickname: _self.UserNickname,
                        Pwd: _self.Pwd2,
                        Remark: _self.Remark,
                        Tel: _self.Tel,
                        RoleId: _self.RoleId,
                        sex: _self.sex,
                        Email: _self.Email,
                        DeptId: _self.DeptId
                    };
                    yui.$axiospostform('/User/AddOrUpdate', data)
                        .then(function (response) {
                            if (response.data.Item1 === 101) {
                                layer.tips(response.data.Item2, '.layui-layer-setwin', {
                                    tips: [1, '#3595CC'],
                                    time: 3000
                                });
                                layer.close(index);
                                return false;
                            }
                            if (response.data.Item1) {
                                layer.msg(response.data.Item2, { icon: 1, time: 1000 });
                                setTimeout(function () {
                                    yui.layer_close3();
                                }, 500);
                            } else {
                                layer.msg(response.data.Item2, { icon: 5 });
                            }
                            layer.close(index);
                        })
                        .catch(function (error) {
                            layer.close(index);
                        });
                }
            }
        });
    </script>
}

src/KopSoftWms/Views/User/Info.cshtml
@{
    Layout = "_LayoutH";
    @model Sys_user
}
<div id="app" v-cloak>
    <form class="form-horizontal" onsubmit="return false">
        <div class="box-body">
            <table class="table table-bordered">
                <tr>
                    <td>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><span class="c-red">*</span>用户名：</label>
                            <div class="col-sm-10">
                                <input v-model="UserName" readonly type="text" class="form-control">
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="control-label col-sm-2"><span class="c-red">*</span>昵称：</label>
                            <div class="col-sm-10">
                                <input type="text" readonly v-model="UserNickname" class="form-control">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><span class="c-red">*</span>电话：</label>
                            <div class="col-sm-10">
                                <input v-model="Tel" readonly type="text" class="form-control">
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="control-label col-sm-2"><span class="c-red">*</span>邮箱：</label>
                            <div class="col-sm-10">
                                <input type="text" readonly v-model="Email" class="form-control">
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <div class="input-group">
                            <input class="form-control" placeholder="请选择图像" v-model="fileName" v-focus type="text">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button" v-on:click="fileL">选择图像</button>
                            </span>
                        </div>
                        <input class="file" style="display:none" ref="fileClick" v-on:change="changeL($event)" accept="image/*" name="file" v-focus type="file">
                    </td>
                </tr>
            </table>
            <div class="box-footer">
                <div class="pull-right box-tools">
                    <input v-on:click="uploadHeadImg" class="btn btn-primary radius" type="submit" v-model="submit">
                </div>
            </div>
        </div>
    </form>
</div>
@section scripts{
    <script>
        var app = new Vue({
            el: "#app",
            data: {
                submit: "修改图像",
                UserName: "@Model.UserName",
                UserNickname: "@Model.UserNickname",
                Tel:"@Model.Tel",
                Email: "@Model.Email",
                param: [],
                acceptFile: [".png", ".jpg",".jpeg",".gif"],
                fileName: '',
            },
            methods: {
                fileL: function () {
                    this.$refs.fileClick.click();
                },
                uploadHeadImg: function () {
                    var _self = this;
                    if (_self.param.length <= 0) {
                        layer.msg("请选择图像", { icon: 2 });
                        return false;
                    }
                    var index = layer.load(1, {
                        shade: [0.1, '#fff'] //0.1透明度的白色背景
                    });
                    axios.post('/User/UploadHeadImg', _self.param, {
                        headers: {
                            'Content-Type': 'multipart/form-data',
                            'fileExcel': 'fileExcel'
                        }
                    }).then(function (response) {
                        if (response.data.Item1 === 101) {
                            layer.tips(response.data.Item2, '.layui-layer-setwin', {
                                tips: [1, '#3595CC'],
                                time: 3000
                            });
                            layer.close(index);
                            return false;
                        }
                        if (response.data.Item1) {
                            layer.msg(response.data.Item2, { icon: 1, time: 1000 });
                            setTimeout(function () {
                                yui.layer_close3();
                            }, 500);
                        } else {
                            layer.msg(response.data.Item2 || errorMsg, { icon: 5 });
                        }
                        layer.close(index);
                    }).catch(function (error) {
                        layer.close(index);
                    });
                },
                changeL: function (e) {
                    var file = e.target.files[0];
                    var _self = this;
                    if (file.size > 0) {
                        _self.param = new FormData();
                        _self.param.append('file', file);
                        _self.fileName = file.name;
                    }
                }
            }
        });
    </script>
}